export const GET_GROUPS_BEGIN = "GET_GROUPS_BEGIN";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_ERROR = "GET_GROUPS_ERROR";
export const GET_GROUP_BEGIN = "GET_GROUP_BEGIN";
export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";
export const GET_GROUP_ERROR = "GET_GROUP_ERROR";
export const SET_SELECTED_GROUP = "SET_SELECTED_GROUP";
